### ISSUE TITLE
404 not found issue

### ISSUE THREAD

**Issue by gp4r** [OSC/bc_osc_codeserver#3] opened 2020-06-24 15:06 UTC
Hello 

I was testing code-server on our OOD but got 404 not found error.

Some reason the redirect URL has "rnode/udc-aw37-23d/26361/" twice like this;
https://rivanna-portal-dev.hpc.virginia.edu/rnode/udc-aw37-23d/26361/rnode/udc-aw37-23d/26361/

If I manually modify the URL to https://rivanna-portal-dev.hpc.virginia.edu/rnode/udc-aw37-23d/26361/, I can see VS page.
Any idea how to solve this issue?

Didn't modify the "view.html.erb"
```
<form action="/rnode/<%= host %>/<%= port %>/login" method="post" target="_blank">
  <input type="hidden" name="password" value="<%= password %>">
  <button class="btn btn-primary" type="submit">
    <i class="fa fa-cogs"></i> Connect to Code Server
  </button>
</form>
```

When I click an existing session, it went to /login but got a white page. removing "login" from URL showed VS page.

Best,
Gisoo

**Comment by SpontaneousDuck** [comment] 2020-06-29 16:49
I also saw this problem. The issue is with the restructuring of `code-server` work is being done to solve this problem in #2 . I was able to change `view.html.erb` with the changes in that PR and everything worked for me.

**Comment by msquee** [comment] 2020-06-29 16:53
@gp4r I've been working on a branch to fix this here https://github.com/OSC/bc_osc_codeserver/pull/2. You could pull in changes from #2 and have a working `code-server` app, there's a few changes that I'm going to make before this can be pushed into master but for the most part its ready to use

**Comment by SpontaneousDuck** [comment] 2020-06-29 16:54
Thanks @gp4r !!

**Comment by ericfranz** [comment] 2020-07-20 14:40
Merged @msquee's PR. There are a few improvements that can still be done but this branch was significantly better - and working. Please open another issue if you find problems with the latest version!

**Closed by ericfranz** 2020-07-20 14:40 UTC
